(server-start)
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(setq inibit-startup-message t)
(when (display-graphic-p)
(org-babel-load-file (expand-file-name "~/.emacs.d/myinit1.org"))
)
